dist: trusty
os: linux
sudo: required

addons:
    apt:
        packages:
            - ghc

before_script:
    - echo "Before build"
    - echo "1. one" >> ~/.htask
    - echo "2. two" >> ~/.htask
    - echo "3. three" >> ~/.htask
    - echo "4. four" >> ~/.htask

script: 
    - ./build.sh
    - ./htask next

after_success:
    - echo "SUCCESS!"

    
