dist: trusty
os: linux
sudo: required

addons:
    apt:
        packages:
            - ghc

before_script:
    - echo "Before build"
    - echo "This is config file." >> ~/.htask

script: 
    - ./build.sh
    - ./htask

after_success:
    - echo "SUCCESS!"

    
