dist: trusty
os: linux
sudo: required

addons:
    apt:
        packages:
            - ghc

before_script:
    - echo "Before build"

script: 
    - ./build.sh
    - ./htask

after_success:
    - echo "SUCCESS!"

    